import Head from 'next/head';
import { useState } from 'react';
import { Inter } from '@next/font/google';

// Components
import Options from '@/components/Options';
import Clock from '@/components/Clock';
import Button from '@/components/Button';

// hooks
import { useTimer } from '@/hooks/useTimer';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  const [isRunning, setIsRunning] = useState(false);

  const time = useTimer({
    isRunning,
    initialTime: 900,
  });

  const handleStart = () => {
    setIsRunning(!isRunning)
  };

	return (
		<>
			<Head>
				<title>Pomodoro</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='w-full h-screen bg-chestnut'>
				<div className='w-screen h-screen flex justify-center items-center px-1'>
					<div className='grid w-full h-2/3 py-5 px-3 rounded-2xl bg-chestnut-300 text-white'>
						{/* Lista de opciones */}
						<Options />
						{/* Contador */}
						<Clock time={time} />
						{/* Acciones */}
						<Button onClick={handleStart} isRunning={isRunning} />
					</div>
				</div>
			</main>
		</>
	);
}
